#define CONTRACTOR_BORG_ICON 'code/modules/antagonists/traitor/contractor/icons/contractor_borg.dmi'
#define CONTRACTOR_ACTIONS_ICON 'code/modules/antagonists/traitor/contractor/icons/contractor_actions.dmi'
#define CONTRACTOR_BORG_ICON_SIZE 48
#define CONTRACTOR_HOVER_TRAIT "contractor_hover"
#define CONTRACTOR_CHASSIS_TRAIT "contractor_chassis"
#define CONTRACTOR_CLOAK_COST (0.15 * STANDARD_CELL_CHARGE)
#define CONTRACTOR_HOVER_COST (0.05 * STANDARD_CELL_CHARGE)
#define CONTRACTOR_HOVER_UPKEEP (0.005 * STANDARD_CELL_CHARGE)
#define CONTRACTOR_CLOAK_ALPHA 0
#define CONTRACTOR_CLOAK_ALLY_ALPHA 50
#define CONTRACTOR_CLOAK_BUMP_ALPHA 40
#define CONTRACTOR_CLOAK_FLARE_TIME (2 SECONDS)
#define CONTRACTOR_CLOAK_FADE_TIME (0.5 SECONDS)
#define CONTRACTOR_CLOAK_DEPLOY_TIME (1.5 SECONDS)
#define CONTRACTOR_DISRUPT_TIME (0.6 SECONDS)
#define CONTRACTOR_TASER_SPINUP (2 SECONDS)
#define CONTRACTOR_STASIS_EFFECT "contractor_chassis"
#define CONTRACTOR_INGEST_TIME (0.6 SECONDS)
#define CONTRACTOR_STRUGGLE_TIME (4 SECONDS)
#define CONTRACTOR_OPEN_TIME (1.2 SECONDS)
#define CONTRACTOR_RESIST_TIME (30 SECONDS)
#define CONTRACTOR_BOOT_FLASH_TIME (0.3 SECONDS)
#define CONTRACTOR_BOOT_FADE_TIME 4
#define CONTRACTOR_GRID_ALPHA_LOW 35
#define CONTRACTOR_GRID_ALPHA_HIGH 80
#define CONTRACTOR_WALK_LINGER 3
